### ISSUE TITLE
Missing argument for parameter 'inContext' in call

### ISSUE THREAD

**Issue by deivuh** [SugarRecord/SugarRecord#108]
I was using an older version of SugarRecord, but I just updated to the latest revision of the code, and I'm getting these compiler errors.

`/SugarRecord/library/CoreData/Base/NSManagedObject+SugarRecord.swift:178:27: Missing argument for parameter 'inContext' in call`

`/SugarRecord/library/CoreData/Base/NSManagedObject+SugarRecord.swift:275:24: Could not find member 'beginWriting'`

`/SugarRecord/library/CoreData/Base/NSManagedObject+SugarRecord.swift:286:24: Could not find member 'endWriting'`

`/SugarRecord/library/CoreData/Base/NSManagedObject+SugarRecord.swift:295:24: Could not find member 'cancelWriting'`

Not sure if there was anything I missed.

**Comment by pepibumur** [comment]
Let me see the lines where that errors are returned! @deivuh

**Comment by deivuh** [comment]
Sure, these are on their respective order. 

`return all().count()`

`self.context().beginWriting()`

`self.context().endWriting()`

`self.context().cancelWriting()`

**Comment by pepibumur** [comment]
@deivuh take a look to the tests or example project because there the following calls are working:
- **Count:** https://github.com/SugarRecord/SugarRecord/blob/develop/spec/Models/CoreDataObjectTests.swift#L47
- **Begin/EndWriting:** https://github.com/SugarRecord/SugarRecord/blob/develop/spec/Models/CoreDataObjectTests.swift#L48
- **CancelWriting:** https://github.com/SugarRecord/SugarRecord/blob/develop/spec/Models/CoreDataObjectTests.swift#L162
Take a look to them. Sorry for the changes but I have had to do some recent refactors to bring more features to the library and to both, Realm and CoreData @deivuh
