### ISSUE TITLE
Missing SugarRecordResults method 

### ISSUE THREAD

**Issue by deivuh** [SugarRecord/SugarRecord#114]
According to [this wiki entry](https://github.com/SugarRecord/SugarRecord/wiki/Operations), the SugarRecordResults class should have a `realCollection()` method which returns the source collection. 

Also, it is also the SugarRecordResults appears to be a generic type class: 

`public class SugarRecordResults<T>: SequenceType...`

But the current implementation is a non-generic class: 

`public class SugarRecordResults: SequenceType...`

**Comment by pepibumur** [comment]
@deivuh when you execute find() the object returned is a SugarRecordResults object with your results. You can iterate over it like if it was an array. Could you try it?

**Comment by deivuh** [comment]
Thanks @pepibumur, and yes, it can be iterated. But it'd be great if it were generic, so I can specify the type of the objects it contains and use them without casting.

**Comment by pepibumur** [comment]
@deivuh tried it but is not as easy at it seems because of the architecture. Try to did it with generics but it involved generics in other SugarRecord components and finally a kind of chain difficult to deal with. I'll keep thinking if there's an easy way to have it. 
Otherwise, if you think about CoreData it returns an [AnyObject] array and leaves to the user responsibility the casting.

**Comment by pepibumur** [comment]
BTW @deivuh SugarRecord is working with Cocoapods. Take a look to the Wiki ;)

**Comment by deivuh** [comment]
Okay @pepibumur, no problem with the casting, was just for convenience. Let me know if there's any way I can help if I'm able to. 

About Cocoapods, I did try it, but I got an issue. Will open another one right now

Thanks for your work! :)
