### ISSUE TITLE
iCould support 

### ISSUE THREAD

**Issue by aatanosv-appolica** [SugarRecord/SugarRecord#68]
Which iOS version for iCloud is supported iOS 7, iOS 8 or both. And is there some specific steps to add iCloud support different from just change the CoreDataStack and enable iCloud?

**Comment by dchavezlive** [comment]
Hey @aatanosv-appolica,
I think this issue has been resolved now. Please take a look at https://github.com/SugarRecord/SugarRecord/pull/128 where I applied a fix to what I believe is the same issue you are currently having. I have also added an iCloud example to the demo and have added some more details on the wiki page. Let me know if the problem is fixed for you.
